package com.bk.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.id
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.parent_id
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.type
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.COMMENTATOR
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Long commentator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.gmt_create
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.gmt_modified
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.like_count
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_comment.content
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.id
     *
     * @return the value of co_comment.id
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.id
     *
     * @param id the value for co_comment.id
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.parent_id
     *
     * @return the value of co_comment.parent_id
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.parent_id
     *
     * @param parentId the value for co_comment.parent_id
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.type
     *
     * @return the value of co_comment.type
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.type
     *
     * @param type the value for co_comment.type
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.COMMENTATOR
     *
     * @return the value of co_comment.COMMENTATOR
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Long getCommentator() {
        return commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.COMMENTATOR
     *
     * @param commentator the value for co_comment.COMMENTATOR
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setCommentator(Long commentator) {
        this.commentator = commentator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.gmt_create
     *
     * @return the value of co_comment.gmt_create
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.gmt_create
     *
     * @param gmtCreate the value for co_comment.gmt_create
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.gmt_modified
     *
     * @return the value of co_comment.gmt_modified
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.gmt_modified
     *
     * @param gmtModified the value for co_comment.gmt_modified
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.like_count
     *
     * @return the value of co_comment.like_count
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.like_count
     *
     * @param likeCount the value for co_comment.like_count
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_comment.content
     *
     * @return the value of co_comment.content
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_comment.content
     *
     * @param content the value for co_comment.content
     *
     * @mbg.generated Wed Apr 29 15:50:03 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}